# Generated by Django 4.1 on 2024-05-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('course_type', models.CharField(max_length=50)),
                ('car_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
