# Generated by Django 4.1 on 2024-05-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_app', '0002_appointment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='appointee',
        ),
    ]
