# Generated by Django 4.1 on 2024-05-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_app', '0015_alter_application_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='country',
            new_name='county',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='id_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
